CarCatalog.Web/Areas/Admin/Controllers/CarController.cs
using CarCatalog.Services.Data.Interfaces;
using CarCatalog.Web.Areas.Admin.ViewModels.Car;
using CarCatalog.Web.Infrastructure.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace CarCatalog.Web.Areas.Admin.Controllers
{
    public class CarController : BaseAdminController
    {
        private readonly ICarSellerService carSellerService;
        private readonly ICarBuyerService carBuyerService;
        private readonly ICarService carService;

        public CarController(ICarSellerService carSellerService, ICarService carService, ICarBuyerService carBuyerService)
        {
            this.carSellerService = carSellerService;
            this.carService = carService;
            this.carBuyerService = carBuyerService;
        }

        public async Task<IActionResult> Mine()
        {
            string? sellerId = 
                await this.carSellerService.GetSellerIdByUserIdAsync(this.User.GetId()!);

            string? buyerId =
                await this.carBuyerService.GetBuyerIdByUserIdAsync(this.User.GetId()!);

            MyCarsViewModel viewModel = new MyCarsViewModel()
            {
                AddedCars = await this.carService.AllCarsBySellerIdAsync(sellerId!),
                CarsBought = await this.carService.AllCarsByBuyerIdAsync(buyerId!),
            };

            return this.View(viewModel);
        }
    }
}

CarCatalog.Web/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace CarCatalog.Web.Areas.Admin.Controllers
{
    public class HomeController : BaseAdminController
    {
        public IActionResult Index()
        {
            return this.View();
        }
    }
}

CarCatalog.Web/Controllers/HomeController.cs
using CarCatalog.Services.Data.Interfaces;
using Microsoft.AspNetCore.Mvc;
using static CarCatalog.Common.GeneralApplicationConstants;

namespace CarCatalog.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ICarService carService;

        public HomeController(ICarService carService)
        {
            this.carService = carService;
        }

        public async Task<IActionResult> Index()
        {
            if (this.User.IsInRole(AdminRoleName))
            {
                return this.RedirectToAction("Index", "Home", new { Area = AdminAreaName });
            }

            var cars = await carService.AllCarsAsync();
            return View(cars);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error(int statusCode)
        {
            if (statusCode == 400 || statusCode == 404)
            {
                return View("Error404");
            }

            if (statusCode == 401)
            {
                return View("Error401");
            }

            return this.View();
        }
    }
}

CarCatalog.Web/Views/Home/Error401.cshtml
@{
    ViewData["Title"] = "Error";
}

<div class="text-center">
    <img src="https://handsontek.net/images/SharePoint/401/401.png"/>
    <h3>
        You need authorization to access this page! Return to the home page or contact the site owner.
        <br />
        <a asp-controller="Home" asp-action="Index">Home</a>
    </h3>
</div>

CarCatalog.Web/Views/Home/Error404.cshtml
@{
    ViewData["Title"] = "Error";
}

<div class="text-center">
    <img src="https://lh6.googleusercontent.com/Bu-pRqU_tWZV7O3rJ5nV1P6NjqFnnAs8kVLC5VGz_Kf7ws0nDUXoGTc7pP87tyUCfu8VyXi0YviIm7CxAISDr2lJSwWwXQxxz98qxVfMcKTJfLPqbcfhn-QEeOowjrlwX1LYDFJN"/>
    <h3>
        The page you were looking for is not found! Check the URL or return to the home page.
        <br />
        <a asp-controller="Home" asp-action="Index">Home</a>
    </h3>
</div>

CarCatalog.Web/Views/Home/Index.cshtml
@using CarCatalog.Services.Data.Interfaces
@model IEnumerable<IndexViewModel>

@{
    ViewData["Title"] = "Home Page";
    var cars = Model.ToList();
}
@if (!cars.Any())
{
    <div class="mt-4 p-5 bg-light">
        <h1 class="display-4">Welcome to the best place for buying cars!</h1>
        <p class="lead">
            Currently there are not any cars for sale. You can enter as a seller and you can make a new offer!
        </p>
        <hr class="my-4">
        <p class="lead">
            @if (User.Identity?.IsAuthenticated ?? false)
            {
                <a asp-controller="Car" asp-action="Add" class="btn btn-primary btn-lg"
           role="button">Sell a Car</a>
            }
        </p>
    </div>
}

<div class="mb-5"></div>

<div class="container text-center">
    <div class="row">
        @for (int i = 0; i < cars.Count(); i++)
        {
            var car = cars[i];
            @if (cars.Count() - 1 == i)
            {
                <div class="col-12">
                    <img class="d-block w-100" style="height:700px"
                 src="@car.ImageUrl" alt="@car.Brand @car.Model">
                </div>

                <div>
                    <h5>
                        <a class="btn btn-primary" asp-controller="Car" asp-action="Details"
                   asp-route-id="@car.Id"> @car.Brand @car.Model</a>
                    </h5>
                </div>
            }
            else
            {
                <div class="col-12">
                    <img class="d-block w-100" style="height:700px"
                 src="@car.ImageUrl" alt="@car.Brand @car.Model">
                </div>

                <div>
                    <h5>
                        <a class="btn btn-primary" asp-controller="Car" asp-action="Details"
                   asp-route-id="@car.Id"> @car.Brand @car.Model</a>
                    </h5>
                </div>

                <div class="mb-5"></div>
            }
        }
    </div>
</div>